### ISSUE TITLE
CompaSOHaloCatalog object creation fails with asdf 4.1.0

### ISSUE THREAD

**Issue by marcelo-alvarez** [abacusorg/abacusutils#170]
CompaSOHaloCatalog object creation fails with asdf 4.1.0 but works with 3.1.0.

In a conda environment at NERSC after installing abacusutils with pip
```
% pip install abacusutils
...
...
Installing collected packages: asdf, abacusutils
Successfully installed abacusutils-2.0.1 asdf-4.1.0
```
I tried to run
```
from abacusnbody.data.compaso_halo_catalog import CompaSOHaloCatalog
catpath = "/global/cfs/cdirs/desi/public/cosmosim/AbacusSummit/AbacusSummit_base_c000_ph000/halos/z0.100"
cat = CompaSOHaloCatalog(catpath,fields='N')
```
but got the error
```
Traceback (most recent call last):
  File "minimal-example-asdf-fail.py", line 3, in <module>
    cat = CompaSOHaloCatalog(catpath,fields='N')
  File ".../python3.10/site-packages/abacusnbody/data/compaso_halo_catalog.py", line 220, in __init__
    with asdf.open(self.halo_fns[0], lazy_load=True, copy_arrays=False) as af:
TypeError: open_asdf() got an unexpected keyword argument 'copy_arrays'
```

I was able to avoid this error either by rolling back to an earlier version of asdf:
```
pip install asdf==3.1.0
```
or removing the seven instances of `copy_arrays` arguments to `asdf.open`  in `compaso_halo_catalog.py`. Sticking with the older version of asdf is the cleaner solution to me and works fine, but I'm reporting it here in case it's helpful.

**Comment by marcelo-alvarez** [comment]
I just saw #157 about this after posting above so it looks like it may have been already addressed. Sorry for the noise if so!

**Comment by marcelo-alvarez** [comment]
I confirmed that #157 solved the problem above by installing the most recent commit:
```
pip install git+https://github.com/abacusorg/abacusutils
...
...
Installing collected packages: asdf, abacusutils
Successfully installed abacusutils-2.0.2.dev72+g6947516 asdf-4.1.0
```
Closing the issue now.

**Comment by lgarrison** [comment]
Sorry you ran into this; we should probably make a release so this stops happening to people. I'll try to do that this week.

**Comment by lgarrison** [comment]
I've released v2.1.0 so PyPI installs should work properly again.

**Comment by marcelo-alvarez** [comment]
Thanks very much!
